- name: Reload haproxy service
  service:
    name: haproxy
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: Reload haproxy

- name: Wating for ports connected
  wait_for:
    host: "0.0.0.0"
    port: "{{ item }}"
    timeout: 30
  with_items:
    - "{{ haproxy_mysql_rw_port }}"
    - "{{ haproxy_mysql_ro_port }}"
  listen: Reload haproxy
