- hosts: masters:slaves
  become: yes
  serial: 33%
  vars_files:
    - vars/mysql_settings.yml
  roles:
    - deploy.MysqlServer

- hosts: masters:slaves
  become: yes
  vars_files:
    - vars/mysql_settings.yml
  tasks:
    - include_role:
        name: deploy.MysqlServer
        tasks_from: check_replication
    - name: make sure ~/.my.cnf is deleted
      file:
        path: ~/.my.cnf
        state: absent
      changed_when: false
