- block:
    - name: Checking chronyd status | RedHat
      service:
        name: chronyd
        state: started
  rescue:
    - name: Installing chrony | RedHat
      yum:
        name: chrony
  always:
    - name: Update chrony.conf | RedHat
      template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
      notify: Restart chronyd service
    - name: "Fetching /etc/chrony.conf to local directory"
      fetch:
        src: "/etc/chrony.conf"
        dest: "install_report/chrony/{{ inventory_hostname }}_chrony.conf"
        fail_on_missing: false
        flat: yes
  when: ansible_os_family == 'RedHat'

- block:
    - name: Checking chrony status | Debian
      service:
        name: chrony
        state: started
  rescue:
    - name: Installing chrony | Debian
      apt:
        name: chrony
  always:
    - name: Update chrony.conf | Debian
      template:
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
      notify: Restart chrony service
    - name: "Fetching /etc/chrony/chrony.conf to local directory"
      fetch:
        src: "/etc/chrony/chrony.conf"
        dest: "install_report/chrony/{{ inventory_hostname }}_chrony.conf"
        fail_on_missing: false
        flat: yes
  when: ansible_os_family == 'Debian'
