- block:
    - name: Checking chrony status
      service:
        name: chronyd
        state: started
  rescue:
    - name: Installing chrony
      package:
        name: chrony
    - name: Set service alias name to 'chronyd'
      ini_file:
        path: /etc/systemd/system/chrony.service.d/alias.conf
        section: Install
        option: Alias
        value: chronyd.service
      when: ansible_os_family == 'Debian'
      notify: Restart chronyd service

- name: Update chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: Restart chronyd service

- name: "Fetching /etc/chrony.conf to local directory"
  fetch:
    src: "/etc/chrony.conf"
    dest: "install_report/chrony/{{ inventory_hostname }}_chrony.conf"
    fail_on_missing: false
    flat: yes
