- block:
    - name: Checking chrony status
      service:
        name: chrony
        state: started
  rescue:
    - name: Installing chrony
      package:
        name: chrony

- name: Update chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: Restart chrony service

- name: "Fetching /etc/chrony.conf to local directory"
  fetch:
    src: "/etc/chrony.conf"
    dest: "install_report/chrony/{{ inventory_hostname }}_chrony.conf"
    fail_on_missing: false
    flat: yes
