- block:
    - name: Checking haproxy status
      service:
        name: haproxy
        state: started
  rescue:
    - name: Installing haproxy
      package:
        name: haproxy

- name: Updating /etc/haproxy/haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: "/usr/sbin/haproxy -c -f %s"
  notify: Reload haproxy

- name: "Fetching /etc/haproxy/haproxy.cfg to local directory"
  fetch:
    src: "/etc/haproxy/haproxy.cfg"
    dest: "install_report/haproxy/{{ inventory_hostname }}_haproxy.cfg"
    fail_on_missing: false
    flat: yes
