- name: Restarting mysqld service
  service:
    name: mysqld
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: Restart mysql

- name: Waiting for mysql started
  wait_for:
    port: "{{ mysql_port }}"
  listen: Restart mysql
