- name: Restarting mysqld service
  service:
    name: mysqld
    state: restarted
    enabled: yes
  listen: Restart mysqld

- name: Restarting mysql service
  service:
    name: mysql
    state: restarted
    enabled: yes
  listen: Restart mysql

- name: Waiting for mysql started
  wait_for:
    port: "{{ mysql_port }}"
  listen: "{{ item }}"
  with_items:
    - Restart mysqld
    - Restart mysql
