- block:
    - name: Checking replication status
      mysql_replication:
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        login_port: "{{ mysql_port }}"
        mode: getslave
      register: slaveStatus
      failed_when: "(slaveStatus.Slave_SQL_Running|bool != true) or (slaveStatus.Slave_IO_Running|bool != true)"
  rescue:
    - pause:
        seconds: 30
        prompt: "Sleep 30s before next check"
    - include_tasks: set_gtid_mode.yml
    - include_tasks: replication.yml
      when: slaveStatus.Slave_IO_Running|bool != true
    - include_tasks: check_replication.yml
