- block:
    - mysql_replication:
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        login_port: "{{ mysql_port }}"
        mode: getslave
      register: slaveStatus
      failed_when: "(slaveStatus.Slave_IO_Running|bool == false) or (slaveStatus.Slave_SQL_Running|bool == false)"
  rescue:
    - pause:
        seconds: 30
    - include_tasks: set_gtid_mode.yml
    - include_tasks: check_replication.yml
