- name: Installing python packages | Debian
  apt:
    name: "{{ item }}"
  with_items:
    - python-mysqldb
    - python-pexpect
  when: ansible_os_family == 'Debian'

- name: Update MySQL root password for all root accounts
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    check_implicit_admin: yes
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}"
    state: present
  with_items:
    - ::1
    - localhost
    - 127.0.0.1

- name: Running mysql_secure_installation
  expect:
    command: /usr/bin/mysql_secure_installation
    responses:
      Enter: "{{ mysql_root_pass }}"
      Press: "y"
      MEDIUM: "1"
      Change: "n"
      Remove: "y"
      Disallow: "y"
      Reload: "y"
    changed_when: false
