# Keep this task as the first task
- name: Uploading my.cnf
  template:
    src: mysql_auth.cnf.j2
    dest: ~/.my.cnf
    mode: 400
  changed_when: false

- include_tasks: "{{ ansible_os_family }}.yml"

- include_tasks: set_gtid_mode.yml
  when: "'masters' in group_names"

- block:
    - name: Get slave running status
      mysql_replication:
        mode: getslave
      register: slaveStatus
      failed_when: "(slaveStatus.Slave_SQL_Running|bool != true) or (slaveStatus.Slave_IO_Running|bool != true)"
  rescue:
    - meta: flush_handlers
    - include_tasks: replication.yml
