# Keep this task as the first task
- name: Uploading my.cnf
  template:
    src: mysql_auth.cnf.j2
    dest: ~/.my.cnf
    mode: 400
  changed_when: false

- include_tasks: "{{ ansible_os_family }}.yml"

- include_tasks: set_gtid_mode.yml
  when: "'masters' in group_names"

# - block:
#     - name: Get slave IO running status
#       mysql_replication:
#         mode: getslave
#       register: slaveIoStatus
#       failed_when: "slaveIoStatus.Slave_IO_Running|bool == false"
#   rescue:
#     - include_tasks: set_gtid_mode.yml
#       delegate_to: slaveIoStatus.Master_Host

- block:
    - name: Get slave SQL running status
      mysql_replication:
        mode: getslave
      register: slaveSqlStatus
      failed_when: "slaveSqlStatus.Slave_SQL_Running|bool == false"
  rescue:
    - meta: flush_handlers
    - include_tasks: replication.yml
