- name: Installing epel-release
  yum:
    name: epel-release

- name: Create mysql yum repository file
  yum_repository:
    name: "mysql{{ mysql_version | replace('.', '') }}-community"
    description: "MySQL {{ mysql_version }} Community Server"
    baseurl: "http://repo.mysql.com/yum/mysql-{{ mysql_version }}-community/el/{{ ansible_distribution_major_version }}/$basearch/"
    enabled: yes
    gpgcheck: no
    # gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
    file: mysql-community

- name: Installing 'mysql-community-server' and 'mysql-community-client'
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - mysql-community-server
    - mysql-community-client
    - MySQL-python
    - python2-pip
  register: install
  until: install is succeeded
  retries: 10
  delay: 10

- name: Install latest 'pexpect'
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - pexpect

- name: Create /var/log/mysql
  file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: 0744

- name: Starting mysqld service
  service:
    name: mysqld
    state: started
    enabled: yes
