# - name: Restarting mysql service
#   service:
#     name: mysql
#     state: restarted
#
# - name: Waiting for mysql started
#   wait_for:
#     port: "{{ mysql_port }}"

- name: Creating user 'repl' for replication
  mysql_user:
    name: "{{ mysql_repl_user }}"
    password: "{{ mysql_repl_pass }}"
    host: '%'
    priv: '*.*:REPLICATION SLAVE'

- name: Stop slave
  mysql_replication:
    mode: stopslave

- name: "Change master to {{ groups['masters'] | select('ne', ansible_hostname) | first  }}"
  mysql_replication:
    master_host: "{{ (groups['masters'] | select('ne', inventory_hostname) | first) }}.node.{{ consul_dc_name }}.consul"
    master_port: "{{ mysql_port }}"
    master_user: "{{ mysql_repl_user }}"
    master_password: "{{ mysql_repl_pass }}"
    master_auto_position: true
    mode: changemaster

- name: Start slave
  mysql_replication:
    mode: startslave

- name: Turn the slaves in read only mode
  mysql_variables:
    variable: read_only
    value: 1
  when: "'slaves' in group_names"
